### ISSUE TITLE
2-tuple coverage issue

### ISSUE THREAD

**Issue by grzegorzgrzegorz** [Cornutum/tcases#10]
Hello TCases team,

Firstly thanks for this great tool. I am really impressed by the simplicity of the idea and incredible range of testing problems it can be applied to. I must tell you I get impressed really seldom :)

I report this as an issue which of course may turn out not to be a defect but...
I have such an input which is 12 combinations total. 

`<?xml version="1.0"?>
<System name="example">
    <Function name="abc">
        <Input type="arg">
            <Var name="input1">
                <Value name="A"/>
                <Value name="B"/>
            </Var>
        </Input>
        <Input type="arg">
            <Var name="input2">
                <Value name="A"/>
                <Value name="B"/>
            </Var>
        </Input>
        <Input type="arg">
            <Var name="input3">
                <Value name="A"/>
                <Value name="B"/>
                <Value name="C"/>
            </Var>
        </Input>
    </Function>
</System>`

After I generated 2-tuple coverage:
`<Generators>
    <TupleGenerator tuples="2"/>
</Generators>`

 I got this:

`<?xml version="1.0"?>
<TestCases system="example">
  <Function name="abc">
    <TestCase id="0">
      <Input type="arg">
        <Var name="input1" value="A"/>
        <Var name="input2" value="A"/>
        <Var name="input3" value="A"/>
      </Input>
    </TestCase>
    <TestCase id="1">
      <Input type="arg">
        <Var name="input1" value="B"/>
        <Var name="input2" value="B"/>
        <Var name="input3" value="B"/>
      </Input>
    </TestCase>
    <TestCase id="2">
      <Input type="arg">
        <Var name="input1" value="A"/>
        <Var name="input2" value="A"/>
        <Var name="input3" value="C"/>
      </Input>
    </TestCase>
    <TestCase id="3">
      <Input type="arg">
        <Var name="input1" value="A"/>
        <Var name="input2" value="B"/>
        <Var name="input3" value="B"/>
      </Input>
    </TestCase>
    <TestCase id="4">
      <Input type="arg">
        <Var name="input1" value="B"/>
        <Var name="input2" value="A"/>
        <Var name="input3" value="A"/>
      </Input>
    </TestCase>
    <TestCase id="5">
      <Input type="arg">
        <Var name="input1" value="B"/>
        <Var name="input2" value="B"/>
        <Var name="input3" value="C"/>
      </Input>
    </TestCase>
    <TestCase id="6">
      <Input type="arg">
        <Var name="input1" value="B"/>
        <Var name="input2" value="A"/>
        <Var name="input3" value="B"/>
      </Input>
    </TestCase>
    <TestCase id="7">
      <Input type="arg">
        <Var name="input1" value="A"/>
        <Var name="input2" value="B"/>
        <Var name="input3" value="A"/>
      </Input>
    </TestCase>
  </Function>
</TestCases>`

Before using TCases I did the example manually and I got 7 test cases. TCases produces 8 test cases. Looking at this output I am able to exclude testcase id=0 because: 
- it contains 3 pairs: AA_, A_A and _AA,
- test case id = 2 already tests AA_ pair,
- test case id = 4 already tests _AA pair,
- test case id = 7 already tests A_A pair,

Could you please explain if this is something I just do not understand about pair-wise testing or maybe some kind of problem in TCases itself?
I use TCases 1.5.4.

Thanks,

Grzegorz

**Comment by kerrykimbrough** [comment]
Hi, Grzegorz

What you're seeing is not unusual. Tcases cannot guarantee that it will produce an absolutely minimal covering set of test cases. In fact, when using the default order of value combination, as you did in your example, the result is often not minimal. As you discovered, you can find a smaller set of test cases that achieves the same coverage.

But you can usually find a smaller covering set by using [random combinations](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#random). In particular, try using the [Tcases Reducer](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#reduce) to automate the search for a smaller set. The result is still not guaranteed to be minimal, but it can usually do better than the default. For example, using the Reducer I was able to get pairwise coverage for your example with only 6 test cases.

**Comment by grzegorzgrzegorz** [comment]
Hello Kerry,

Thanks for explanations. It turns out I need to spend more time on reading documentation. I will definitely try to get the same result of 6 test cases - it sounds very interesting.
