### ISSUE TITLE
NA values

### ISSUE THREAD

**Issue by hiteshmehata** [Cornutum/tcases#11]
Hi,
Don't want "NA" values to appear in output XML. Is there a way to do that?
Regards,
Hitesh

**Comment by kerrykimbrough** [comment]
Hi, Hitesh

Can you explain more? Why do you see NA as a problem? What would you like to see instead?

**Comment by hiteshmehata** [comment]
Though it is not a big problem and we can easily ignore variables with NA value, while executing test case. But I need to write implementation to ignore them while execution. I think it make sense not to include these NA variables as those are not application to the scenario at all.

**Comment by kerrykimbrough** [comment]
I'm not sure how you go from Tcases to "executing a test case". If you are using Tcases output as a guide for manual testing, you might consider generating output in the form of a [HTML report](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#html). NA values are excluded from this HTML report.

**Comment by kerrykimbrough** [comment]
Otherwise, as you mention, it's possible to transform Tcases output to exclude NA values. Consequently, I would not propose to add any special new features to do this.

**Comment by hiteshmehata** [comment]
I am writing a java program which read the tCases output and generate the required Javascript for me. I think as it is simple to exclude the NA values programmatically, I will close this issue.
