### ISSUE TITLE
OpenAPI:  Doesn't handle request authentication

### ISSUE THREAD

**Issue by kerrykimbrough** [Cornutum/tcases#115]
Authentication requirements defined in the OpenAPI spec are not incorporated into generated input models or test programs.

**Comment by mimkorn** [comment]
Hi, does that mean you can't run the tests against an authenticated API?

**Comment by kerrykimbrough** [comment]
Fixed by PR #195. Documentation details TBD.

**Comment by kerrykimbrough** [comment]
This fix is now available in version 3.7.0. For details, see the [release notes](https://github.com/Cornutum/tcases/blob/master/ReleaseNotes.md#370),
