### ISSUE TITLE
Command not worked for me 'tcases-api petstore-expanded.yaml'

### ISSUE THREAD

**Issue by ksrajith** [Cornutum/tcases#119]
1. Clone the porject using 'https://github.com/Cornutum/tcases.git'
2. Went to '/tcases/tcases-openapi' using terminal
3. Executed command :  'tcases-api petstore-expanded.yaml'
4. Got below error
'tcases-api' is not recognized as an internal or external command,
operable program or batch file.
![image](https://user-images.githubusercontent.com/16276648/84982465-64849080-b154-11ea-9c66-63f6a616a58d.png)

5. But this should works as per the 'https://github.com/Cornutum/tcases/tree/master/tcases-openapi#then-use-tcases-to-generate-your-api-test-cases'

**Comment by ksrajith** [comment]
Please note: 
'mvn tcases:api' able to run the suite but needs to know why this failed for above command

**Comment by kerrykimbrough** [comment]
Hi, it looks like you need to add the Tcases `bin` directory to your PATH environment variable. This  detail is described in the [installation instructions](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#install).

**Comment by kerrykimbrough** [comment]
Looking closer, I think I see part of the misunderstanding. To run Tcases commands, you need to download and install the Tcases binary distribution. 

Or build your own copy of the release distribution. For example, the following command creates a copy of the binary distribution package in `tcases-shell\target`.

```
cd tcases
mvn clean install -pl tcases-shell -am -DskipTests
```

**Comment by kerrykimbrough** [comment]
Assuming this explanation fixed the problem.

**Comment by rkariyawas** [comment]
Can I know why I getting below error even the class is exists
![image](https://user-images.githubusercontent.com/60919528/85544556-c05d8680-b638-11ea-8bc6-8cbdeb27c154.png)

**Comment by kerrykimbrough** [comment]
Are you running this command from an installation of the Tcases binary
package? If so, does the path to your installation directory contain any
space characters? If so, you are seeing a known problem, which is fixed by
the current (unreleased) version of the tcases-api(.bat) command.

**Comment by kerrykimbrough** [comment]
Are you running this command from an installation of the Tcases binary
package? If so, does the path to your installation directory contain any
space characters? If so, you are seeing a known problem, which is fixed by
the current (unreleased) version of the tcases-api(.bat) command.

**Comment by ksrajith** [comment]
Hi Kerry,
Thank you verymuch
I able to run after config the path variable,
But I have two consers 
1. I used 'petstore-expanded.yaml' file and change the server url,
As Per the docs api invokes to actual enviroment, but same request and response jsons generated to invalid server url.
2. I saw in the doc 'Defining System Functions' But I can not find such a file and appriciate if you can expalin it further

**Comment by kerrykimbrough** [comment]
Sorry, I don't clearly understand the problem below. Can you create a new issue for this? Please include a description of steps to reproduce the problem.

> 1. I used 'petstore-expanded.yaml' file and change the server url,
>    As Per the docs api invokes to actual enviroment, but same request and response jsons generated to invalid server url.

**Comment by kerrykimbrough** [comment]
> 2. I saw in the doc 'Defining System Functions' But I can not find such a file and appriciate if you can expalin it further

This section explains how to create a "system input definition" file. But when you are using Tcases for OpenAPI this system input definition is generated automatically, usually as temporary intermediate result, in which case no such file is created. But if you want to see what it looks like, try this command:

```
tcases-api -I -T yaml < petstore-expanded.yaml 
```

**Comment by ksrajith** [comment]
created

> > 1. I saw in the doc 'Defining System Functions' But I can not find such a file and appriciate if you can expalin it further
> 
> This section explains how to create a "system input definition" file. But when you are using Tcases for OpenAPI this system input definition is generated automatically, usually as temporary intermediate result, in which case no such file is created. But if you want to see what it looks like, try this command:
> 
> ```
> tcases-api -I -T yaml < petstore-expanded.yaml 
> ```

created issues and looking for your guide
