### ISSUE TITLE
Open api yaml file not executed against the real end points and always returns the same response json

### ISSUE THREAD

**Issue by ksrajith** [Cornutum/tcases#120]
Re-creation steps
1. Add 'petstore-expanded.yaml' for tcases-openapi repo
2. Execute it 'mvn tcases:api' can ge the request and response json files from target folder.
3. Change the 'petstore-expanded.yaml   servers.url' attribute as: 'http://petstore.swagger.aaaaaaaaaaa/api' and saved.
4. Execute it 'mvn tcases:api' and can ge the new request and response json files from target folder.
5. Compare the response json files in step 2 and step 4
6. Both files are identical even they executed for diffrent endpoints.
As per the read me 'petstore-expanded.yaml' should executed against its real endpoints which is mentioned under 'servers.url'.
But even the url changed to invalid one it returns same response json

**Comment by kerrykimbrough** [comment]
I could not reproduce this problem. After `mvn tcases-api`, I see the the changed value for the server URL.

Which version of the tcases-maven-plugin are you using?

**Comment by ksrajith** [comment]
pom file has below properties 
   <groupId>org.cornutum.tcases</groupId>
        <artifactId>tcases</artifactId>
        <version>3.4.1-SNAPSHOT</version>

> I could not reproduce this problem. After `mvn tcases-api`, I see the the changed value for the server URL.
> 
> Which version of the tcases-maven-plugin are you using?

   <groupId>org.cornutum.tcases</groupId>
        <artifactId>tcases</artifactId>
        <version>3.4.1-SNAPSHOT</version>

 <groupId>org.cornutum.tcases</groupId>
                <artifactId>tcases-maven-plugin</artifactId>
                <version>${tcases.maven.version}</version>

**Comment by ksrajith** [comment]
please note command is  mvn tcases:api
![image](https://user-images.githubusercontent.com/16276648/85879046-4cb5a800-b7f7-11ea-9485-adb8b31de8be.png)

**Comment by kerrykimbrough** [comment]
Yes, I meant to write `mvn tcases:api`.

I used the 3.4.0 release version, but it should be the same. I don't think this is a Tcases problem. Try looking for some other reason why you don't see the expected change.

**Comment by ksrajith** [comment]
So If the 'value for the server URL' is changed to invalid url then response file should be generated only with error status isn't it ?

**Comment by kerrykimbrough** [comment]
Tcases for OpenAPI just copies the URL exactly as shown in the OpenAPI spec. It does not check to see if this URL is valid.

**Comment by kerrykimbrough** [comment]
Clarified expected result
