### ISSUE TITLE
Can you explain further what does mean by 'Tcases reads a system input definition'

### ISSUE THREAD

**Issue by ksrajith** [Cornutum/tcases#121]
1. Where can I find the system inpun file mentioned in 'http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#systemInputDef'
2. We are not much clear on explanation under 'Defining System Functions' So is possible to have more explanation.
3. Please let us know any screen recordings, or more materials avilable for fresh users.

**Comment by kerrykimbrough** [comment]
This section explains how to create a "system input definition" file. But when you are using Tcases for OpenAPI, this system input definition is generated automatically, usually as temporary intermediate result, in which case no such file is created. But if you want to see what it looks like, try this command:

```
tcases-api -I -T yaml < petstore-expanded.yaml 
```

**Comment by kerrykimbrough** [comment]
In other words, when you are using Tcases for OpenAPI, you really don't have to know about the Tcases system input definition file. Instead, all input information is taken from the OpenAPI definition.

**Comment by kerrykimbrough** [comment]
Clarified expected result
