### ISSUE TITLE
'tcases -help' command returns an Error

### ISSUE THREAD

**Issue by ksrajith** [Cornutum/tcases#122]
1. clone the tcase (3.4.1)
2. configured build path in windows
3. executed 'tcases -help' as per the 'http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#systemInputDef'
4. returns below error
![image](https://user-images.githubusercontent.com/16276648/85881032-9b187600-b7fa-11ea-9859-bbcbe04e8c14.png)

**Comment by kerrykimbrough** [comment]
For the Windows version, it's not really an error. That is just how help information is shown.

But I agree that this should be improved.

**Comment by ksrajith** [comment]
Thanks @kerrykimbrough 
This is really grate repo

**Comment by kerrykimbrough** [comment]
Fixed by PR #126

**Comment by kerrykimbrough** [comment]
Fix now available in release 3.4.1
