### ISSUE TITLE
How to derive test cases in junit and testNG formats from given yaml

### ISSUE THREAD

**Issue by ksrajith** [Cornutum/tcases#123]
Lets think we have 'petstore-expanded.yaml' file.
And we can generate requst and resonse jsons using above yaml file,
But need to know steps for the derive above requests and responses to junit and testNg formats.
Tried out 'tcases -J < find-Input.xml' command and its explantion not much make sense, So like to know more clear steps

**Comment by kerrykimbrough** [comment]
The basic result of Tcases is a test case _definition_. This is just a description of selected input values and is not directly executable. The `-J` option will show test case definitions in the form of empty JUnit/TestNG methods, with the descriptions in Javadoc and other comments. For example, `tcases-api -J -T yaml < petstore-expanded.yaml` or `mvn tcases:api -Djunit=true`.

To get executable test cases, try `tcases-api-test -T yaml -p org.cornutum.examples < petstore-expanded.yaml ` or `mvn tcases:api-test`. For more explanation, see [this document](https://github.com/Cornutum/tcases/blob/master/tcases-openapi/Running-Api-Test-Cases.md#generating-executable-tests).

**Comment by ksrajith** [comment]
This can be success with below commnad and created junit test cases
tcases\tcases-openapi>tcases-api-test -o target/generated-test-sources/java/org/testapp src/test/tcases/openapi/org/testapp/pets
tore-expanded.yaml

**Comment by kerrykimbrough** [comment]
Yes, this produces JUnit tests. If you want tests for TestNG, add `-t testng`.

**Comment by ksrajith** [comment]
So above I mentioned command executed without mvn and like to know is it posible to generate java class using mvn command and with targetdirectory and sourcefile(yaml)

Also like to know is it possible to execute the generated out put class file as junit test class

**Comment by kerrykimbrough** [comment]
Yes, it is certainly possible to compile and run the generated JUnit test class. Of course, you will need to download the REST Assured library as a dependency.

**Comment by kerrykimbrough** [comment]
> This can be success with below commnad and created junit test cases
> tcases\tcases-openapi>tcases-api-test -o target/generated-test-sources/java/org/testapp src/test/tcases/openapi/org/testapp/pets
> tore-expanded.yaml

The equivalent Maven command would be this:

```
mvn tcases:api-test
```

For details, see the [plugin documentation](http://www.cornutum.org/tcases/docs/tcases-maven-plugin/api-test-mojo.html).

**Comment by kerrykimbrough** [comment]
Clarified expected result
