### ISSUE TITLE
Generate response json file with 200 OK , even the server Url is invalid in the yaml file

### ISSUE THREAD

**Issue by rkariyawas** [Cornutum/tcases#128]
1. Change server url of the pet-store yaml file.
2. Generate request and response jsons using pet-store yaml.
3. The generated response JSON file contains success responses with 200 OK (This can not be happen if the response json file generated using given server url).
4. So Why response JSON file contains success responses even the server URL is invalid

**Comment by kerrykimbrough** [comment]
This is the expected result. To determine the validity of the server URL, a request must be executed. But Tcases for OpenAPI doesn't execute API requests -- it just converts an input document (the OpenAPI description) into an output document (the API test cases).

**Comment by rkariyawas** [comment]
But in the document, it mentioned that the yaml file executes for its endpoints when generating the response.json file.
So I thought its executes at that point and generate the response json file base on the actual responses

**Comment by kerrykimbrough** [comment]
Can you point me to the location in the documentation where you saw this? Perhaps some clarification is needed there.

**Comment by rkariyawas** [comment]
Can You please check this
![image](https://user-images.githubusercontent.com/60919528/86189956-a5bb6e00-bb60-11ea-925c-5942bafd79f2.png)

**Comment by kerrykimbrough** [comment]
This describes a 2-step process. 

1. First you run Tcases for OpenAPI (using the method explained in "Running API Test Cases"), which produces the source code for a test program. 

1. Then you build and run the test program, which executes API requests. 

So if the server URL is invalid, you won't find out until you complete the 2nd step.

**Comment by rkariyawas** [comment]
Thanks Kerry,
I will check this
