### ISSUE TITLE
Only generating the GET method tests

### ISSUE THREAD

**Issue by mhettiarac** [Cornutum/tcases#131]
I have used this command to generate the junit tests : mvn tcases:api-test -DtestPackage=src.test.tcases.openapi.org.app.petstore
The issue is it only generates the GET route tests only.. Ideally it should generate tests for Post and other contract endpoints as well in the API Spec.
Please find the attached screenshot and the project herewith..

![image](https://user-images.githubusercontent.com/51822287/86618866-3d90e000-bfd7-11ea-8054-106ed71efe9a.png)

Sample test project:
[TcasesSampleMaven.zip](https://github.com/Cornutum/tcases/files/4880257/TcasesSampleMaven.zip)

**Comment by kerrykimbrough** [comment]
The reason is shown in the log messages:

```
[WARNING] Swagger Petstore: No inputs to model for operation=POST_pets.
```

Typically, a POST request will provide input in a request body. But no request body is defined.

Without some kind of input definition (parameters or request body), Tcases has nothing to work with. Although such requests are valid and should be handled. I'll open a different issue for that problem.

**Comment by mhettiarac** [comment]
@kerrykimbrough  We have couple of questions need your input to get clarified.. Can you let us know a feasible time maybe, so we can have a call through teams, skype, hangout or anything you are comfortable with... Thanks much!

**Comment by rkariyawas** [comment]
But POST requests exist on the '[petstore-expanded.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml)' file and the generated request json.

**Comment by kerrykimbrough** [comment]
@mhettiarac Yes, I can meet via Microsoft Teams. It appears you may be located in the India Standard Time zone. If so, perhaps you could set up a meeting for your Thu 7/9 at 8:30 AM. That will be at the end of the day in my time zone, which is a good time for me. Please email the invite to me at kerrykimbrough@gmail.com.

**Comment by mhettiarac** [comment]
Hi @kerrykimbrough 7/9 is bit late for us since we have a demo to be present on that day on our findings about the tool.. Is there a possibility to have the call right now? We are available for another one hour time and we can have a call if you are comfortable.

**Comment by kerrykimbrough** [comment]
@mhettiarac  OK, let's meet now.

**Comment by mhettiarac** [comment]
Please connect to
Join Microsoft Teams Meeting 

https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTIyZTI0NmQtNTM4NS00NTViLWE4ZjQtNTAyMjBkNTNlNDJi%40thread.v2/0?context=%7b%22Tid%22%3a%2224fe244f-890e-46ef-be2f-a5202976b7a5%22%2c%22Oid%22%3a%22fac1b134-1215-4448-bfd1-601966579924%22%7d
