### ISSUE TITLE
Which java version is the recomnded to setup tcases

### ISSUE THREAD

**Issue by rkariyawas** [Cornutum/tcases#145]
Got few maven errors while try with JDK 1.8.0_265
like java-doc null poniter 

and few other...
 tcases-openapi: Could not resolve dependencies for project org.cornutum.tcases:tcases-openapi:jar:3.4.3-SNAPSHOT: The following artifacts could not be resolved: org.cornutum.tcases:tcases-io:jar:3.4.3-SNAPSHOT, org.cornutum.tcases:tcases-io:jar:tests:3.4.3-SNAPSHOT: Could not find artifact org.cornutum.tcases:tcases-io:jar:3.4.3-SNAPSHOT

**Comment by rkariyawas** [comment]
I can only resolve the  below
tcases-openapi: Could not resolve dependencies for project org.cornutum.tcases:tcases-openapi:jar:3.4.3-SNAPSHOT: The following artifacts could not be resolved: org.cornutum.tcases:tcases-io:jar:3.4.3-SNAPSHOT, org.cornutum.tcases:tcases-io:jar:tests:3.4.3-SNAPSHOT: Could not find artifact org.cornutum.tcases:tcases-io:jar:3.4.3-SNAPSHOT

And I just ignore the java-doc null poniter issue
using               <failOnError>false</failOnError>

**Comment by kerrykimbrough** [comment]
For any unresolved problem, please create a new issue that describes exactly what went wrong and how to reproduce the problem.
