### ISSUE TITLE
ApiTestCommand should create additional test cases using OpenAPI examples 

### ISSUE THREAD

**Issue by kerrykimbrough** [Cornutum/tcases#151]
Suggested by @rkariyawas 

The examples defined by the OpenAPI spec could be used to generate additional test cases. The examples can be used to designate specific test cases not otherwise covered by the Tcases generation process.

**Comment by kerrykimbrough** [comment]
@rkariyawas Thanks for prompting this issue

**Comment by rkariyawas** [comment]
Hi Kerry,
Is this possible to address through Tcases it would be great,
Then we can continue our test case generation through Teases.

**Comment by kerrykimbrough** [comment]
Resolved by PR #156

**Comment by kerrykimbrough** [comment]
@rkariyawas Fixed in Release 3.5.0
