### ISSUE TITLE
[Junit] Too many constraints error

### ISSUE THREAD

**Issue by codingsoo** [Cornutum/tcases#168]
Hi,

When a swagger file is big, it generates too many constraints error.

I think this is because Junit has limited constraints pool. I tried this project: https://github.com/devgateway/ocvn

**Comment by codingsoo** [comment]
If you try running a swagger file with 500 testsperoperation option, you could easily reproduce the bug. To solve this problem, I think the number of Junit tests should be limited or splitted.

**Comment by kerrykimbrough** [comment]
Sorry, I don't understand what you mean by "too many constraints error". Can you explain? Better yet, can you show a reproducible test case?

**Comment by codingsoo** [comment]
[tcases_ocvn.zip](https://github.com/Cornutum/tcases/files/6481358/tcases_ocvn.zip)
Hi, the constant pool includes numbers, strings, method names, field names, class names, references to classes and methods. The limit is 65536, so it needs to be split when it exceeds it. I attached the file which is generated by Tcases for the OCVN REST API web service.

**Comment by kerrykimbrough** [comment]
The best solution is to control the size of the generated test by controlling the amount of the API that is covered. For example, you might consider generating separate tests for each API path. 

```
# Generate tests only for operations on /myResource
tcases-api-test -P /myResource myApiSpec.json
```

Or if using Maven:
```
# Generate tests only for operations on /myResource
mvn tcases:api-test -Dpaths=/myResource -Dproject=myApiSpec
```

**Comment by codingsoo** [comment]
Hi, thank you for your solution.

I think exercising each API path should work, but in my case, there are too many end-points in the swagger file (https://github.com/codingsoo/temp_swagger/blob/main/ocvn.json).

Could I know if you have a plan to add a feature for exercising a fat swagger file's all API path?

**Comment by kerrykimbrough** [comment]
I'm considering adding an option to automatically generate a separate test class for each API path. Would that resolve your problem?

**Comment by codingsoo** [comment]
Sure! I really appreciate it!

**Comment by kerrykimbrough** [comment]
@codingsoo, unless you have any further requests, I plan to produce a new release containing the 2 new features you suggested.

**Comment by codingsoo** [comment]
Thank you very much! I really like this project.

**Comment by kerrykimbrough** [comment]
Fixed by PR #173

**Comment by kerrykimbrough** [comment]
@codingsoo, FYI, a new release 3.6.0 containing your suggested features is now available

**Comment by codingsoo** [comment]
I will use 3.6.0! Thank you very much:) Hope you have a wonderful day.
