### ISSUE TITLE
[Suggestion] Add timeout to the Junit

### ISSUE THREAD

**Issue by codingsoo** [Cornutum/tcases#171]
Hi,

I am really enjoying learning this tool.

If the server holds the request and does not give any response, the Junit test wait the response forever.

I think adding an option like Schemathesis' "--request-timeout" would help to resolve this problem. I think this function can be easily added by the Junit's timeout rule.

Thank you!

**Comment by kerrykimbrough** [comment]
Good idea! To be addressed in next release

**Comment by kerrykimbrough** [comment]
Fixed by PR #172
