### ISSUE TITLE
Value already defined for variable

### ISSUE THREAD

**Issue by AnirudhChaudhary** [Cornutum/tcases#178]
Hello,
I am trying to generate test cases for my OpenApi spec with your tool but Tcases is erroring when I run the program against my spec. I get IllegalStateException stating that the value is already defined. I have attached a picture of the error message that I am getting.

Is this an error caused by the spec?

Thanks for your time.
Below are two different error reports for two different APIs.
![TCases_Error_ClientReporting](https://user-images.githubusercontent.com/52807055/122301956-4b710580-ceb6-11eb-93bc-f6c0b94a2467.JPG)

![Tcases_Error](https://user-images.githubusercontent.com/52807055/122301391-7c9d0600-ceb5-11eb-9d89-55440905855f.JPG)

**Comment by kerrykimbrough** [comment]
Please attach the OpenAPI documents that can be used to reproduce this problem

**Comment by AnirudhChaudhary** [comment]
Hello Kerry,
I don't have access to the entire document to send to you but I do have a picture of the section of the code where the error is popping up.
![ClientReportingPost](https://user-images.githubusercontent.com/52807055/122484588-bfc8a900-cf89-11eb-998a-5a1aec006efd.JPG)

**Comment by kerrykimbrough** [comment]
Thanks for the update. This problem appears to arise from the way the `application/*+json` media type is handled. Look for a fix in the next release.

**Comment by AnirudhChaudhary** [comment]
Thanks for the response. Do you have an estimate for when such a release would come out? Is there a schedule to releases?

**Comment by kerrykimbrough** [comment]
Now fixed in release 3.6.1
