### ISSUE TITLE
Value already defined for variable P2

### ISSUE THREAD

**Issue by AnirudhChaudhary** [Cornutum/tcases#182]
Hello,
I've downloaded the latest version of Tcases (3.6.1) and I am once again running into the same error that I was running into in the previous version.

Please advise. Thanks for your time.
![ClientReportingPostError361](https://user-images.githubusercontent.com/52807055/122791460-18d85b80-d26e-11eb-9a70-3ea854aa222e.JPG)

**Comment by kerrykimbrough** [comment]
To be sure you're running the right version, run `tcases-api -v`

**Comment by AnirudhChaudhary** [comment]
When I ran tcases-api -v, I got an output saying that I am running 3.6.0. I have downloaded the new version from the Maven Central Repository Search. 
How can I get the new version?

**Comment by kerrykimbrough** [comment]
Looks like you need to add the new release bin directory to your PATH. You can find more details [here](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#install).

**Comment by AnirudhChaudhary** [comment]
Yes doing this worked for me. Thank you :)
