### ISSUE TITLE
execution command gives error 

### ISSUE THREAD

**Issue by arjunashetty** [Cornutum/tcases#209]
1)  I am getting following error when I try to run from command line 
                   cmd : `tcases-api-test`
                   error : Error: Could not find or load main class org.cornutum.tcases.openapi.ApiTestCommand

2) When i try to run from maven :  mvn tcases:api 
                           error : 
                           No plugin found for prefix 'tcases' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/../.m2/repository), releases (.../artifactory/plugins-release), snapshots (../artifactory/plugins-snapshot), central (https://repo.maven.apache.org/maven2)]

**Comment by kerrykimbrough** [comment]
> 1. I am getting following error when I try to run from command line
>    cmd : `tcases-api-test`
>    error : Error: Could not find or load main class org.cornutum.tcases.openapi.ApiTestCommand

Did you [download and install](http://www.cornutum.org/tcases/docs/Tcases-Guide.htm#install) the Tcases command line package for the latest release? Did you add the Tcases `bin` directory to the `PATH` variable for your command shell?

**Comment by kerrykimbrough** [comment]
> 2. When i try to run from maven :  mvn tcases:api
>    error :
>    No plugin found for prefix 'tcases' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/../.m2/repository), releases (.../artifactory/plugins-release), snapshots (../artifactory/plugins-snapshot), central (https://repo.maven.apache.org/maven2)]

Did you add the `tcases-maven-plugin` to the `plugins` list in the `pom.xml` file for your project?

**Comment by kerrykimbrough** [comment]
With no responses and no further information, I presume this issue has been resolved.

**Comment by arjunashetty** [comment]
@kerrykimbrough  yes, i tried all the mentioned steps, please check the screenshots :

**Comment by arjunashetty** [comment]
![image](https://user-images.githubusercontent.com/46148141/134276739-dbdff8dc-4ec4-4097-b3cc-2a1192f660bd.png)

**Comment by kerrykimbrough** [comment]
The mvn command screenshot shows that the tcases-maven-plugin is not available in your Maven project. Possibly it is not listed in the <plugins> section of the project POM. Or possibly it could not be downloaded from any of the repos defined for this project.

**Comment by kerrykimbrough** [comment]
The shell command screenshot is inconclusive. Not sure why the last line does not use "export".  Are you using `bash` for your shell program? Or some different shell program?

To see more info, you might try running something like this:

```
bash -x `which tcases-api` -v
```

**Comment by kerrykimbrough** [comment]
Also, you might try something like this:

```
bash -x `which tcases-exec` tcases-api org.cornutum.tcases.openapi.ApiCommand -v
```

**Comment by kerrykimbrough** [comment]
To see more info about your Maven project plugins, try this:

```
mvn help:effective-pom
```

**Comment by arjunashetty** [comment]
getting this error, I have downloaded tcases shell from : https://search.maven.org/search?q=tcases-shell, 
![Screenshot 2021-09-23 at 11 16 51 AM](https://user-images.githubusercontent.com/46148141/134459903-667badd5-ac73-496b-be20-389b3ac01af0.png)

**Comment by kerrykimbrough** [comment]
The latest screenshot shows that `tcases-exec` is being located in `/Users/arjun/Documents/tcasesFramework/tcases/tcases-shell/bin`. This looks suspiciously like a directory in a git repository. If so, that will fail in exactly the way shown here. 

You should be finding `tcases-exec` within a Tcases installation directory. I suspect your `PATH` variable is misconfigured, so that `tcases-exec` is being found in the wrong directory. Your `PATH` should contain a directory path that looks something like `.../tcases-3.7.1/bin`. Your previous screenshot shows a `PATH` like this, although it actually contains 3 different directories of that form, which is clearly confused. I recommend you start with a fresh shell environment and fix your scripts to set up the `PATH` correctly.
