### ISSUE TITLE
getting command not found 

### ISSUE THREAD

**Issue by arjunashetty** [Cornutum/tcases#210]
getting following error : 
arjun@Arjuns-MBP bin % tcases-api
Error: Could not find or load main class org.cornutum.tcases.openapi.ApiCommand

Operating sys : MAC OS

**Comment by kerrykimbrough** [comment]
See discussion for issue #209

**Comment by arjunashetty** [comment]
commented on  thread #209 , kindly check

**Comment by kerrykimbrough** [comment]
Duplicate of #209
