### ISSUE TITLE
MediaRange does not accept space after semicolon

### ISSUE THREAD

**Issue by neofreko** [Cornutum/tcases#237]
on version 3.8.1
Per [w3 spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), the can be space after semicolon. Eg:
`audio/*; q=0.2, audio/basic`

In my case, I found it when server returns:
`application/json; charset=utf-8`

However, current implementation fails on above example.

Probable fix:
`([^\s\/]+)\/([^\s+;]+)(?:\+([^\s;]+))?((?:;\s*[^\s;=]+=(?:[^\s";=]+|"(?:[^\"]|\\.)*"))+)?`

**Comment by kerrykimbrough** [comment]
You're right. Although the media range grammar doesn't show it, HTTP basic rules allow "linear white space" (LWS) between tokens and separators. Will fix soon in next release.

**Comment by kerrykimbrough** [comment]
Fixed in release 3.8.2
