### ISSUE TITLE
Cleanup ITestCaseGenerator - TupleGenerator api conflict.

### ISSUE THREAD

**Issue by tkruse** [Cornutum/tcases#24]
ITestCaseGenerator does not have public API methods e.g. to set tuple size. But tcases command has option:

```
-c tupleSize | If -c is defined, use the given default tupleSize for all generators.
```

So something is wrong with ITestCaseGenerator (How to add a custom ITestCaseGenerator implementation to a generatorSet that will accept a tupleSize argument). Same for setting combiners in ITestCaseGenerator. Not sure how to best fix this, since I don't know if there are any other Generators than the TupleGenerator.

**Comment by kerrykimbrough** [comment]
This is intentional. Tuple and combiners are one way to generate test cases. But some generators could work differently.
