### ISSUE TITLE
Allow any String as Variable Value, not just identifiers

### ISSUE THREAD

**Issue by tkruse** [Cornutum/tcases#25]
Currently Tcases only allows variable values that are valid identifiers according to DefUtils.isIdentifier, meaning matching the regex ```"[\\w\\-]+"``` (alphabetic letters, numbers, underscores, hyphens).

However, for unit testing, special symbols are frequently part of the input to test. The Tcases restriction forces test designers to always map from abstract identifiers of values to actual values.

A PR shows one way to achieve this #27

For escaping/unescaping, commons-lang3 has StringEscapeUtils.

EDIT: complely rewrote the bug description.

**Comment by tkruse** [comment]
Note I can patch by subclassing VarValueDef and overriding setName/getName if I am desperate.

**Comment by tkruse** [comment]
I could patch VarValueDef without too much pain, but it's also used in ```new Varbinding()``` called From TestCase, which is much worse to patch.

**Comment by kerrykimbrough** [comment]
I'm not eager to change this requirement. Too many complexities would be involved, and I don't see any real benefit.

**Comment by tkruse** [comment]
Basically, there is no excuse for validating a value as an identifier. Those are different concepts. As another example, currently you allow raw numbers as identifiers, and strings containing hyphens as identifiers. As opposed as an example to Java identifiers. So maybe tcases currently is too relaxed for actual identifiers, but much too strict for mere values.

About the "real" benefit, where to start: 
* Imagine testers in Asian or Arabic countries, wont they prefer to use actual test values like すずき?
* Or imagine writing a tests for a keyboard (real or virtual), or anything taking and input string with special chars. The current limitation prevents users from specifying the string values they want to test with directly.
* Or imagine a test for mathematical expressions.

About the effort for escaping / unescaping is part of the xml standard, I believe the parser would not even have to be changed. Only the XML Writer needs to escape. See #27

**Comment by tkruse** [comment]
Did you reconsider after my explanation?

**Comment by kerrykimbrough** [comment]
Yes, I  agree now this is a useful improvement.
