### ISSUE TITLE
Testcases in a sheet

### ISSUE THREAD

**Issue by arjunashetty** [Cornutum/tcases#258]
Hi Team, 

Can we get generated testcases for the APIs in a readable format like in an excel sheet / google doc ?

**Comment by kerrykimbrough** [comment]
Sounds like this could be done with a special TestWriter, using the [TestWriter API](https://github.com/Cornutum/tcases/blob/master/tcases-openapi/Running-Api-Test-Cases.md#understanding-the-testwriter-api). Care to give it a try?

If you imagine spreadsheet format, what would it look like?

**Comment by arjunashetty** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/46148141/202283977-bde5586d-39a4-4f60-aff3-9b904649a4e6.png">
I wanted to use tcases to generate test cases in this format

**Comment by arjunashetty** [comment]
could you please help with this utility, i am not well versed with testwriterAPI yet. also let me know any proper tutorial where i can understand the testwriterAPI
