### ISSUE TITLE
Modification of tCases

### ISSUE THREAD

**Issue by benedict-miguel-dev** [Cornutum/tcases#274]
Currently. the values that tCases generates is valid based on schema but may or may not be invalid input. For example, suppose we have a parameter named "Country: String", tCases generates test cases to where Country is a valid string. However, it may generate a "Country: ThisIsNotACountry" which is not a valid country and causes the generated test case to fail because the server sees the value as an invalid country. but tCases sees this as valid because it is according to specification. Is it possible to modify tCases such that it is able to allow pass this test case?

**Comment by kerrykimbrough** [comment]
You might consider changing the schema to specify an `enum` listing all of the valid country names.

**Comment by benedict-miguel-dev** [comment]
This is true, however I’m interested in the case that we can’t define it. For example, a name or an ID.

**Comment by kerrykimbrough** [comment]
In those cases, you might consider a schema that defines valid values using a `pattern`.

**Comment by benedict-miguel-dev** [comment]
I suppose that there is no way at all to do it without the use of patterns?

**Comment by kerrykimbrough** [comment]
Currently, a schema is the only way to define the set of valid values.
