### ISSUE TITLE
TestWriter: Decimal values given in the example are ignored in the generated tests

### ISSUE THREAD

**Issue by sundarlogan** [Cornutum/tcases#289]
Tcases Version: 4.0.2
OpenAPI Version: 3.0.0
OpenAPI Spec File: Attached - [openapi-example.json](https://github.com/Cornutum/tcases/files/14223997/openapi-example.json)
Writing API tests using `TestNgTestWriter[] and RestAssuredTestCaseWriter[]

We have a decimal value in example for post api call field --  "paymentAmount": 10.03. In the generated test body, decimal value .03 is ignored.
 
![image](https://github.com/Cornutum/tcases/assets/119917413/7d77fb01-1510-41df-a079-761f70deafdb)

**Comment by sundarlogan** [comment]
@kerrykimbrough Can you pls. help with this, did we missed anything here or any other way to define decimals.

**Comment by kerrykimbrough** [comment]
Investigating now. Stay tuned.

**Comment by kerrykimbrough** [comment]
I have found the source of the problem, which also exists in the latest version=4.0.3. A fix will be coming soon. 

BTW, why are you not using version 4.0.3?

**Comment by kerrykimbrough** [comment]
Fixed in release 4.0.4

**Comment by sundarlogan** [comment]
Thank you @kerrykimbrough ..
