### ISSUE TITLE
Optional import should be there else creating issue in generated Junit

### ISSUE THREAD

**Issue by pankajgupta-web** [Cornutum/tcases#297]
https://github.com/Cornutum/tcases/blob/b6c6f4fdb9619ad265879cffe719a9542343b422/tcases-rest-assured/src/main/java/org/cornutum/tcases/openapi/restassured/RestAssuredTestCaseWriter.java#L60

targetWriter.println( "import java.util.Optional;"); 

should be there before 

targetWriter.println( "import static java.util.stream.Collectors.*;");

**Comment by kerrykimbrough** [comment]
I'm not sure I understand the problem. Can you explain what is going wrong?
