### ISSUE TITLE
Allow non-English words in identifiers

### ISSUE THREAD

**Issue by kerrykimbrough** [Cornutum/tcases#30]
It should be possible to use non-English words as identifiers in all components of a SystemInputDef

**Comment by kerrykimbrough** [comment]
For Tcases, an "identifier" is intended to be a sequence of one or more words or numbers, separated by either hyphen or underscore. Currently defined by the regex `[A-Za-z0-9_-]+`. I'm thinking of changing this to `[\p{isAlphabetic}\p{isDigit}_-]+`. But I'm not sure how well this works for Japanese and Chinese character sets. @tkruse, any advice?

**Comment by tkruse** [comment]
See here: https://stackoverflow.com/questions/14636540/java-regular-expression-with-international-letters

**Comment by tkruse** [comment]
Though for System *name* and function *name*, maybe the concept of a *name* is different from that of an *identifier*. What makes an identifier special to me is that it can be evaluated in expressions (such as boolean expressions or method invocations etc.). For properties and even variable names, it seems acceptable that they might need to be processed in other larger expressions. So they need *identifiers* not just *names*.

**Comment by kerrykimbrough** [comment]
Fixed by PR #32
