### ISSUE TITLE
How to generate concrete test cases?

### ISSUE THREAD

**Issue by ClayGminx** [Cornutum/tcases#301]
I tried to generate test cases using the Tcases and I got a JSON file. But values in the JSON file weren't concrete. For example, value for integer type variable is `< 0`, and value for string type variable is that `Value.Length` is `> 0`. Can I get concrete value? For example, value for integer type variable is `-1`, and value for string type variable is `a`.

**Comment by kerrykimbrough** [comment]
If you define a variable value using a [schema](https://github.com/Cornutum/tcases/blob/master/Tcases-Guide.md#defining-value-schemas), Tcases will generate concrete values matching the schema. Often it is simpler to define the variable itself using a [variable schema](https://github.com/Cornutum/tcases/blob/master/Tcases-Guide.md#defining-variable-schemas), in which case Tcases will also automatically create value definitions that generate concrete values.
