### ISSUE TITLE
Allow VarVaueDef to contain null values.

### ISSUE THREAD

**Issue by tkruse** [Cornutum/tcases#35]
For TestCases involving null or undefined as a variable input, it is clumsy and error-prone to have to encode null as a String value in XML. E.g. testing String values [null, "", "a", ...], whichever value is chosen to represent null (such as "null"), it can easily later be mistaken for the String "null" rather than a null value, and overlooking this might hide bugs.

Ideally the SystemInputDef and SystemTestDef would also be able to represent null values. In XML this could be achieved by merely allowing tags without a "value" attribute, or by having a new attribute similar to NA in TCases 2.0.0.

Discussed at https://github.com/Cornutum/tcases/issues/34

**Comment by kerrykimbrough** [comment]
Resolved by PR #39
