### ISSUE TITLE
Provide programmatic Reducer API

### ISSUE THREAD

**Issue by tkruse** [Cornutum/tcases#36]
Hi,

so far I have not looked much at the Reducer class. For using it from my beanfiller project, it needs to be refactored to allow reducing based on the Java classes, not files. So the second half of the huge Reducere.run() method should be extracted, possibly with it's own Options class similar to what was done for the Tcases class.

**Comment by kerrykimbrough** [comment]
Agreed

**Comment by kerrykimbrough** [comment]
Resolved by PR #41
