### ISSUE TITLE
Issue When creating org.cornutum.tcases.VarDef variables with UTF-8 encoded string

### ISSUE THREAD

**Issue by OmalW** [Cornutum/tcases#47]
Issue When creating org.cornutum.tcases.VarDef variables with UTF-8 encoded string. This will give below error,
java.lang.IllegalArgumentException: "???" is not a valid identifier
at org.cornutum.tcases.DefUtils.assertIdentifier(DefUtils.java:46)
	at org.cornutum.tcases.VarValueDef.setName(VarValueDef.java:95)
	at org.cornutum.tcases.VarValueDef.<init>(VarValueDef.java:84)
	at org.cornutum.tcases.VarValueDef.<init>(VarValueDef.java:76)

I'm using 1.5.4 version

**Comment by OmalW** [comment]
Thanks for the update @kerrykimbrough. Is there a documentation for java where i can follow. (2.1.2 version is bit different from 1.5.4)

**Comment by kerrykimbrough** [comment]
Not sure what kind of documentation you're looking for. Can you clarify?

**Comment by kerrykimbrough** [comment]
Starting in 2.0.0, the public methods in `Tcases.java` were refactored to improve modularity at the `Function` level of processing. Using this API, it's now possible to directly convert an individual `FunctionInputDef` into a single `FunctionTestDef` without creating a `SystemInputDef`. To support this, there is now a new form of `annotateTests` that operates [solely at the `Function` level](https://github.com/Cornutum/tcases/blob/9ba5fa72e17212dce99eade68f8edbf251f32a2f/tcases-lib/src/main/java/org/cornutum/tcases/Tcases.java#L126). 

But when processing a `SystemInputDef`, annotations at the `System` level are propagated to each `FunctionTestDef`. Therefore, there is an [additional form of `annotateTests` ](https://github.com/Cornutum/tcases/blob/9ba5fa72e17212dce99eade68f8edbf251f32a2f/tcases-lib/src/main/java/org/cornutum/tcases/Tcases.java#L168)to handle this.

You can see how this works by looking at [the `getTests` method ](https://github.com/Cornutum/tcases/blob/9ba5fa72e17212dce99eade68f8edbf251f32a2f/tcases-lib/src/main/java/org/cornutum/tcases/Tcases.java#L37)that converts a `SystemInputDef` into a `SystemTestDef`.

**Comment by OmalW** [comment]
Thank you vary much @kerrykimbrough. You save my day...
