### ISSUE TITLE
Input model variable order respect

### ISSUE THREAD

**Issue by juglar** [Cornutum/tcases#5]
I would clearly prefer that the order of appearance of the variables in each test case totally respected the order in which I define them in the Input.xml file, independently of the Input section in which they are included. 

It would give me total control over that order, which will help me make the variables correctly correspond to argument positions in a test function call when transformed by the xsl. 

If there is another reason to reorder them that I don’t see now, at least, I think it would be very convenient to have an option to make tcases strictly respect the input model file order.

**Comment by kerrykimbrough** [comment]
It's important to group output variable bindings by Input type. Indeed, the main purpose of Input type is allow output transformations to handle different types differently.

If you place the \<Var\> definitions for all function parameters in an \<Input\> group of the same type, then they will will appear together in the same order in the test definition file, just like you want. If you need to transform some of these Vars differently you could give them different \<Has\> annotations.

**Comment by juglar** [comment]
If the main purpose of the input type, as you explain, is to allow different transformations, that feature is lost when one needs variable output order control (as uses to be my case). Yes, now, that feature can be transferred to the Has annotations, so, my request is not really necessary. But it is a convenience to preserve the original input type utility: Actually, it allows more concise and centralized characterization of the grouped variables. Other way of grouping them could be through varset's, but their inclusion of the varset name in the variable paths makes the handling more difficult.

Anyway, I agree that it's not a prioritary modification and that it would be worth just a little effort.

Thanks.

**Comment by kerrykimbrough** [comment]
Tcases will group output variable binding by Input type and, within each \<Input\> group, bindings will be listed in the same order as the \<Var\> definitions in the input model. If some members of the \<Input\> group need to be transformed differently, use \<Has\> annotations. Note that you can have two \<Input\> definitions with the same type but different group-level annotations.
