### ISSUE TITLE
Documentation of Variable Conditions

### ISSUE THREAD

**Issue by juglar** [Cornutum/tcases#7]
Although it can be deducted from the current documentation test, I would add some more explicit remark about the important behavior of Tcases when a variable condition is included for a variable: 

Using “NA” as the variable value when the required condition is not fulfilled would avoid a normal value being “spent” in a combination where it is not really tested and, so, being falsely counted as tested in combination with the values of the other variables in the test case. 

So, it is normal that a bigger number of cases be needed (and generated by Tcases) to achieve the specified coverage.

**Comment by kerrykimbrough** [comment]
Tcases Guide, Combinatorial Testing Basics: Clarify factors that influence test suite size, including use of constraints.
