### ISSUE TITLE
throws an error if the xml file contain special characters   

### ISSUE THREAD

**Issue by marlanfernando** [Cornutum/tcases#8]
if the XML file contain special character other than alphanumerical values tCases throws an exception error mentioning that  the field is not a valid identifier 
![capture](https://cloud.githubusercontent.com/assets/16499569/12063796/f1849960-afda-11e5-90f6-c38358cd6bdb.PNG)
![capture1](https://cloud.githubusercontent.com/assets/16499569/12063811/252a8d60-afdb-11e5-993e-1e2232530a32.PNG)

**Comment by kerrykimbrough** [comment]
True, although it would be more accurate to say that values of "name" attributes are restricted to certain characters. But why do you think this is an issue? Can you explain further?

It's also true that the requirement for "name" values is not really defined anywhere. That's a documentation defect that certainly ought to be fixed. Also, to say that such a value must be an "identifier" is a bit misleading. The [required pattern](https://github.com/Cornutum/tcases/blob/master/tcases-lib/src/main/java/org/cornutum/tcases/DefUtils.java#L79) matches not only normal identifiers (as in Java, C++, etc.) but also integer numbers like "0" and "-123".

**Comment by marlanfernando** [comment]
consider this,
if we want to check a scenario like "amount greater than some value then something happens". 
so we can write that as " amount > 10000 " 
in the xml value it is like " amount &gt; 10000 " this is a valid xml value but in tcases this is rejected due to ampersand is there. so my point is, it is better to check the whole xml not the values inside the xml

**Comment by kerrykimbrough** [comment]
The rule for "name" attributes, etc. is not arbitrary. Part of the rationale is to keep the XML readable as-is, which excludes characters like '<' that must be encoded specially. Also, part of the rationale is to exclude certain characters that are used as value delimiters (for example, period, comma, and space). And finally, just to keep things simple, to limit things to the alphanumeric chars needed to form words and numbers. So far, I have not seen any good reason to change this rule.
