### ISSUE TITLE
Generating test cases for OpenAPi 3.0 using tcases maven plugin

### ISSUE THREAD

**Issue by devdream02** [Cornutum/tcases#82]
Hi Team,

Thanks for the awesome work.

I was wondering if there's a way to generate the junit test caes for openapi3.0 using tcases maven plugin.

or if you could share a code example for generating the test cases using java code.

**Comment by kerrykimbrough** [comment]
The next release will add support for OpenAPI to the Tcases Maven plugin.

**Comment by kerrykimbrough** [comment]
As described in the [guide](https://github.com/Cornutum/tcases/blob/master/tcases-openapi/README.md#using-the-java-api-for-tcases-for-openapi), there are some simple interfaces to do this from a Java program.  You can see an example in the source for [ApiCommand](https://github.com/Cornutum/tcases/blob/master/tcases-cli/src/main/java/org/cornutum/tcases/openapi/ApiCommand.java#L669). Depending on exactly what you want to do, there are just a few steps.

1. Using [TcasesOpenApiIO.getRequestTests](http://www.cornutum.org/tcases/docs/api/org/cornutum/tcases/openapi/io/TcasesOpenApiIO.html#getRequestTests-java.io.File-), read a File or InputStream containing an OpenAPI spec and translate to a `SystemTestDef`, which is the Java representation of the test cases for API requests.
1. Using [TcasesOpenApiIO.writeTests](http://www.cornutum.org/tcases/docs/api/org/cornutum/tcases/openapi/io/TcasesOpenApiIO.html#writeTests-org.cornutum.tcases.SystemTestDef-java.io.OutputStream-), write the test cases to an OutputStream in the form of a JSON document.

**Comment by kerrykimbrough** [comment]
Hmm, I just realized you asked about JUnit test cases. I assume you mean generating Java source code for JUnit tests. That's a more complicated question.

If you mean complete JUnit test methods that are ready for execution, the answer is "No". The output from Tcases for OpenAPI _describes_ the test cases. Or, more precisely, it describes the kind of inputs needed. But the tool doesn't necessarily define the actual concrete input values to use. Nor does it know exactly which tools you will use to set up and invoke HTTP requests. Nor can it possibly know what the expected outputs of each request should be. 

If you mean a JUnit test class skeleton with empty placeholder methods describing each test case, the answer is "Yes", although in the current version the path to that result is a bit of a round-about.

**Comment by kerrykimbrough** [comment]
@devdream02, Can you clarify exactly what you think is needed from Tcases for OpenAPI? Otherwise, I'm not sure what to do with this issue.

**Comment by devdream02** [comment]
Hi @kerrykimbrough apologies for delayed response was out of town for few days. 
Thanks for the clarification though. What i was looking for is the auto generation of test cases in restassured or some other testing framework for all the endpoints described in Open APi sepc file.

**Comment by kerrykimbrough** [comment]
OK, thanks for clarifying. To execute such tests, 4 elements must be complete.

1. The framework for organizing test execution, e.g. JUnit, etc.
1. The interfaces for submitting HTTP requests and receiving responses
1. The actual request inputs
1. The expected response outputs

Automatically generating any of these is problematic, because different people want to do them differently. Tcases has some support for JUnit/TestNG, which are popular in the Java world. But choices for (1) and (2) are numerous, especially in the Javascript world. 

Automatically generating concrete inputs is something I've been thinking about. It might be semi-doable, with some extra help from the test coder.

Automatically generating expected outputs is infeasible. Generally speaking, mathematically undecidable.

Given these limitations, what improvements would you like to see in TFOA?

**Comment by kerrykimbrough** [comment]
Looking closer at rest-assured, I see that it works with JUnit and supplies the elements for (2). That makes it pretty easy to generate. If TFOA can supply the (3) bits, that would get you most of the way home.

**Comment by devdream02** [comment]
> OK, thanks for clarifying. To execute such tests, 4 elements must be complete.
> 
> 1. The framework for organizing test execution, e.g. JUnit, etc.
> 2. The interfaces for submitting HTTP requests and receiving responses
> 3. The actual request inputs
> 4. The expected response outputs
> 
> Automatically generating any of these is problematic, because different people want to do them differently. Tcases has some support for JUnit/TestNG, which are popular in the Java world. But choices for (1) and (2) are numerous, especially in the Javascript world.
> 
> Automatically generating concrete inputs is something I've been thinking about. It might be semi-doable, with some extra help from the test coder.
> 
> Automatically generating expected outputs is infeasible. Generally speaking, mathematically undecidable.
> 
> Given these limitations, what improvements would you like to see in TFOA?

Well you have summarized it well, so the only variable in the equation of your's is point (3) and (4) right. Which can easily be found/extracted from the Open API spec file. As its the API contract which defines all the necessary values, either you can use the example values defined by the person in the spec file or based on the model defined by him you can use some dummy values.

**Comment by kerrykimbrough** [comment]
Replaced by more specific issues #84 and #86
