### ISSUE TITLE
OpenAPI: Generate source for Java tests using  REST Assured

### ISSUE THREAD

**Issue by kerrykimbrough** [Cornutum/tcases#84]
Suggested by @devdream02: Provide an option to generate Java source code for API test cases in the form of JUnit methods that use REST Assured to submit requests and verify responses.

**Comment by ToxicDragon** [comment]
+1 for that! Or at least enable transformations for json input definitions

**Comment by kerrykimbrough** [comment]
> Or at least enable transformations for json input definitions

@ToxicDragon Can you clarify? Do you mean transformation of the current TCFOA output, i.e. JSON test cases? Can you recommend any Java-based tools for JSON transformation?

**Comment by kerrykimbrough** [comment]
Fixed by PR #112

**Comment by kerrykimbrough** [comment]
@devdream02, support for REST Assured is not available in release 3.4.0
