### ISSUE TITLE
The ApiMojo assumes that a custom transformer will always be used to generate JSON output, when not generating Junit or html output

### ISSUE THREAD

**Issue by lintong** [Cornutum/tcases#90]
I'd like to be able to use tcases in order to generate tests for SpringBoot applications.

It would be useful to be able to customise the Junit generating XSLT, with is not currently overridable. Equally, the `ApiMojo.execute()` method never sets the `options.outFile` param, ensuring that `ApiCommand.run()` method generates JSON output whenever Junit or HMTL aren't in use and a custom transformation *is* provided i.e. https://github.com/Cornutum/tcases/blob/5ba062399a97cf0b8adce87c156c9a36718e75e8/tcases-cli/src/main/java/org/cornutum/tcases/openapi/ApiCommand.java#L904

**Comment by kerrykimbrough** [comment]
Hi, @lintong. I think you're pointing out that `ApiCommand` doesn't allow for custom XSLT transforms, as with the `-x` option for `TcasesCommand`. Given that `ApiCommand` now supports standard transforms (`-J` and `-H`), also supporting `-x` probably makes sense. 

I hesitated to do this because TFOA operates in the JSON ecosystem, where the XML representation of test cases doesn't matter and XSLT is an alien creature. On the other hand, as far as I know, there isn't a standard JSON transformation processor. So XML/XSLT is probably the best answer to do what you want.

**Comment by lintong** [comment]
Hi @kerrykimbrough  

I was thinking of taking something akin to this approach anyway since my timescales are fairly short. Please let me know when and if you decide to add this enhancement and I'll refactor my code to suit. Be sure to close this ticket whenever you see fit. Thanks for the assistance.

**Comment by kerrykimbrough** [comment]
I'm working now on adding this support for `-x`. Stay tuned for a new release.

**Comment by kerrykimbrough** [comment]
@lintong,

It occurs to me now that if you need something right away, there is a work-around. By default, `ApiCommand` and `ApiMojo` translate an OpenAPI spec into test case definitions. But they also provide an option to produce just the input definition instead. For `ApiCommand`, this is `-I` ( or `Options.setTests(false)`); for `ApiMojo`, it is `-DinputModels=true`.

Given an input definition, you can handle it via `TcasesCommand` or `TcasesMojo` in the usual way to apply your custom XSLT transform. You could even apply something other than that basic default generator definition, which is something that TFOA itself doesn't do.

**Comment by lintong** [comment]
The following abridged code does the job for me


```
final File apiSpecFile = new File(getInputFile());
            final SystemInputDef inputDef = TcasesOpenApiIO.getRequestInputModel(apiSpecFile, getApiDefType(), null);
            TcasesIO.writeTests(Tcases.getTests(inputDef, null, null), getTransformer().getSource());
...

AbstractFilter getTransformer() throws IOException {
        final File destinationFile = new File(destinationDirectory, outputClassName);
        final AbstractFilter transformer = new DefinitionViaXslFilter(transformation, params);
        transformer.setTarget(destinationFile);
        return transformer;
    }

class DefinitionViaXslFilter extends TransformFilter {

    public DefinitionViaXslFilter(final String transformationFile, final Map<String, Object> params) throws IOException {
        super(getTransformDef(transformationFile), params);
    }

    private static InputStream getTransformDef(final String transformationFile) throws IOException {
        return new FileInputStream(transformationFile);
    }
}

```

Thanks for the assistance @kerrykimbrough

**Comment by kerrykimbrough** [comment]
Nice! That's pretty much what the changes to `ApiMojo`, etc. would do.

**Comment by kerrykimbrough** [comment]
Is it fair to say that, if `ApiMojo` had support for custom XSLT transforms, you would have preferred to use that?
