### ISSUE TITLE
The outcome of FormattedStringTest.whenFormatDateTime() is sensitive to transitions in British Summer time and Daylight Saving

### ISSUE THREAD

**Issue by lintong** [Cornutum/tcases#91]
A bug in the `whenFormatDateTime()` test case means that this test case works for six months of the year only when the codebase is built from the UK. 

Would it be possible for you to provide a concrete expected value for the assertion and switch to a fixed Java 8+ clock, rather than the outcome of this method call please?

https://github.com/Cornutum/tcases/blob/72c32e6bafa22406bb33d0e40a95f5667e4372a9/tcases-openapi/src/test/java/org/cornutum/tcases/openapi/FormattedStringTest.java#L78

**Comment by kerrykimbrough** [comment]
Hi, @lintong. Thanks for reporting this problem. Please let me know if the commit referenced above fixes things for you.

**Comment by lintong** [comment]
Hi @kerrykimbrough 

Thanks for the swift response. The method is making the following assertion and failing:

`Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE!
whenFormatDateTime(org.cornutum.tcases.openapi.FormattedStringTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Date string
Expected: is "2019-08-09T24:59:59.876+01:00"
     but: was "2019-08-10T00:59:59.876+01:00"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.cornutum.tcases.openapi.FormattedStringTest.whenFormatDateTime(FormattedStringTest.java:58)
`

What do you expect the expected value to be?

**Comment by kerrykimbrough** [comment]
I'm a lucky guy! Your local time zone is perfect for exposing the stupidity of my test logic! I think I've got it now. Try pulling master again to pick up this revised commit: https://github.com/Cornutum/tcases/commit/ba3c79d49d337bd52321384b3df16110d1436158

**Comment by lintong** [comment]
Thanks @kerrykimbrough, it looks like it's working now. Please close the issue.
